### ISSUE TITLE
Add 2022 testimonial section to 2023 website

### ISSUE THREAD

**Issue by driesvints** [fullstackeurope/fullstackeurope.com#66]
Add the same testimonial section with tweets from the 2022 website to the 2023 website with the below tweets:

https://twitter.com/joelbutcher97/status/1578718335813885954
https://twitter.com/vanamerongen/status/1578710586053263360
https://twitter.com/maybeFrederick/status/1578709015093125120
https://twitter.com/noctovis/status/1578641231873478656
https://twitter.com/aarondfrancis/status/1578500367771320320
https://twitter.com/mazedlx/status/1578493175031005185
https://twitter.com/mjwhansen/status/1578482334419939330
https://twitter.com/Sjors1985/status/1578453142852685824
https://twitter.com/BurtDS/status/1578424740162994176
https://twitter.com/tvbeek/status/1578416744569327616
https://twitter.com/xiCO2k/status/1578400544850411520
https://twitter.com/KeerthanaK17/status/1578048416210378752
https://twitter.com/RoseSecOps/status/1578324665709498368
https://twitter.com/CasperBE/status/1578401579249565701

**Comment by riasvdv** [comment]
Done!
